"""Sinh Supplementary Material (per-seed tables) từ results/*.csv.
Output: paper_q1_supplementary.md — tái tạo được bằng một lệnh, không copy tay."""
import io, os, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
import pandas as pd

R = r'c:\Users\admin\NCKH\results'
OUT = r'c:\Users\admin\NCKH\paper_q1_supplementary.md'

sections = []
sections.append('# Supplementary Material — per-seed results\n\n'
                '> Auto-generated by `make_supplementary.py`. '
                'Regenerate after any experiment re-run.\n')

def add_pivot(title, csv, index, columns, note=''):
    df = pd.read_csv(os.path.join(R, csv))
    df = df[df.seed >= 0] if 'seed' in df.columns else df
    piv = df.pivot_table(index=index, columns=columns, values='MAE')
    sections.append(f'\n## {title}\n\nSource: `results/{csv}`. {note}\n\n'
                    + piv.round(4).to_markdown())

add_pivot('S1. E13 — PVDAQ resolution sweep (MAE per seed)',
          'e13_multires_sweep.csv', 'seed', ['resolution', 'mode', 'model'],
          'n=20 seeds, post-audit deterministic seeding.')
add_pivot('S2. E13b — PERT cross-site replication (MAE per seed)',
          'e13b_duramat_coarse.csv', 'seed', ['site', 'resolution', 'mode',
                                              'model'],
          'Cells below inclusion thresholds absent by design.')
add_pivot('S3. E13c — wind-availability ablation (MAE per seed)',
          'e13c_ws_ablation.csv', 'seed', ['resolution', 'mode', 'model'])
add_pivot('S4. E13d — classical baselines (MAE per seed)',
          'e13d_classical_baselines.csv', 'seed', ['mode', 'model'],
          'LR/Ridge/Faiman deterministic (seed −1, excluded here).')

e14 = pd.read_csv(os.path.join(R, 'e14_conformal_uq.csv'))
piv = e14.pivot_table(index='seed', columns=['alpha', 'method', 'band'],
                      values='coverage')
sections.append('\n## S5. E14 — conformal coverage per seed\n\n'
                'Source: `results/e14_conformal_uq.csv`.\n\n'
                + piv.round(4).to_markdown())

stats_files = [('S6. E13 statistical tests', 'e13_stats.csv'),
               ('S7. E13b cross-site tests', 'e13b_stats.csv'),
               ('S8. E13c disambiguation tests', 'e13c_stats.csv')]
for title, f in stats_files:
    df = pd.read_csv(os.path.join(R, f))
    sections.append(f'\n## {title}\n\nSource: `results/{f}`.\n\n'
                    + df.round(4).to_markdown(index=False))

sections.append('\n## S9. Hyperparameters\n\n'
                '| Item | Value |\n|---|---|\n'
                '| Optimiser | Adam, lr 1e-3, MSE |\n'
                '| Early stopping | patience 20, restore best |\n'
                '| ReduceLROnPlateau | factor 0.5, patience 10, min 1e-6 |\n'
                '| Max epochs | 200 |\n'
                '| Batch | min(256, max(32, n_fit/60)) |\n'
                '| Validation | last 10% of train (temporal) |\n'
                '| Seeds | range(20), keras.utils.set_random_seed '
                'before build |\n'
                '| PG-ResMLP | 4→32→16→1 ReLU, 705 params |\n'
                '| LSTM | LSTM-64 + Dense-32, dropout 0.1, 20,289 params |\n'
                '| Hybrid | d_model 64, 4 heads, FF 128, LSTM-32, '
                '46,881 params |\n')

with open(OUT, 'w', encoding='utf-8') as f:
    f.write('\n'.join(sections))
print(f'saved {OUT} ({os.path.getsize(OUT)/1e3:.0f} kB)')
